
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grcp-deploymentn
  namespace: practica2-201905837
  labels:
    app: grcpapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grcpapp
  template:
    metadata:
      labels:
        app: grcpapp
    spec:
      hostname: grcp-host
      containers:
      - name: client
        image: amacario502/clientgrcp_201905837
        ports:
        - containerPort: 3000
        env:
        - name: GRCP_SERVER
          value: "grcp-host:50051"

      - name: server
        image: amacario502/servergrcp_201905837
        ports:
        - containerPort: 50051
        env:
        - name: ADD_KAFKA
          value: my-cluster-kafka-bootstrap.kafka:9092
---
apiVersion: v1
kind: Service
metadata:
  name: svc-demo
  labels:
    app: grcpapp
spec:
  type: LoadBalancer
  selector:
    app: grcpapp
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
