
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber-deployment
  namespace: practica2-201905837
  labels:
    app: subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      hostname: grcp-host
      containers:
      - name: subscriber-cont
        image: amacario502/subscriber_201905837
        env:
        - name: ADD_KAFKA
          value: my-cluster-kafka-bootstrap.kafka:9092
